language: python
python:
  - "3.5"
cache: pip
group: edge
services:
  - docker

install:
  - pip install -r requirements.txt
  - chmod +x $TRAVIS_BUILD_DIR/build_kafk.sh
  - $TRAVIS_BUILD_DIR/build_kafk.sh
script:
  - coverage run tests/fb_posts_test.py
  - python tests/integrations_tests.py
after_success:
  - codecov
